#!/usr/bin/env bash

main(){

  if (( "$#" < 1)); then
    echo "Usage: commit [commit-message]"
    exit 1
  fi

	git add .
	git commit -m "$1"
	git push
	doxygen Doxyfile
	sftp root@tech-support.systems << EOF "put -r docs; mv docs /var/www/gamestate-docs"
EOF
	rm -rf docs
}

main "$@"
